spring:
  application:
    # 服务名
    name: service-provider
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 192.168.17.102:8848
server:
  # 服务端口
  port: 8070
#  port: 8060
management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"